-- MySQL Script generated by MySQL Workbench
-- Thu May 20 11:43:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`WishList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WishList` (
  `idWishList` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idWishList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `WishList_idWishList` INT NOT NULL,
  PRIMARY KEY (`iduser`, `WishList_idWishList`),
  INDEX `fk_user_WishList1_idx` (`WishList_idWishList` ASC),
  CONSTRAINT `fk_user_WishList1`
    FOREIGN KEY (`WishList_idWishList`)
    REFERENCES `mydb`.`WishList` (`idWishList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offre` (
  `idOffre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `cateogry` VARCHAR(45) NOT NULL,
  `user_iduser` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idOffre`),
  INDEX `fk_Offre_user_idx` (`user_iduser` ASC),
  INDEX `fk_Offre_product1_idx` (`product_idproduct` ASC),
  CONSTRAINT `fk_Offre_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WishList_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WishList_has_product` (
  `WishList_idWishList` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`WishList_idWishList`, `product_idproduct`),
  INDEX `fk_WishList_has_product_product1_idx` (`product_idproduct` ASC),
  INDEX `fk_WishList_has_product_WishList1_idx` (`WishList_idWishList` ASC),
  CONSTRAINT `fk_WishList_has_product_WishList1`
    FOREIGN KEY (`WishList_idWishList`)
    REFERENCES `mydb`.`WishList` (`idWishList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WishList_has_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
